package com.voyageai.voyageaibackend.domain.model;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Structured representation of a travel itinerary with geographic data for map integration.
 * 
 * <p>This model is designed to support rich frontend interactions:
 * <ul>
 *   <li>Display itinerary in a structured, day-by-day format</li>
 *   <li>Plot all locations on an interactive map (Google Maps)</li>
 *   <li>Enable bidirectional linking: click activity → highlight map marker</li>
 *   <li>Enable reverse linking: click map marker → scroll to activity card</li>
 *   <li>Draw daily routes connecting activity locations</li>
 * </ul>
 * 
 * <p>Data source: Generated by AI (OpenAI GPT-4) with geographic coordinates,
 * optionally enriched with Google Places API for precise location data.
 * 
 * <p>Example structure:
 * <pre>
 * {
 *   "metadata": { "destination": "Tokyo", "totalDays": 5, ... },
 *   "days": [
 *     {
 *       "dayNumber": 1,
 *       "date": "2024-04-01",
 *       "theme": "Tokyo Arrival: Exploring Shinjuku",
 *       "activities": [
 *         {
 *           "activityId": "act-day1-001",
 *           "time": "09:00-11:00",
 *           "title": "Shinjuku Gyoen National Garden",
 *           "location": {
 *             "latitude": 35.6852, "longitude": 139.7103, ...
 *           }
 *         }
 *       ]
 *     }
 *   ]
 * }
 * </pre>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class StructuredItinerary {

  /**
   * Itinerary metadata (overview information).
   */
  private ItineraryMetadata metadata;

  /**
   * Daily itineraries in chronological order.
   */
  private List<DailyItinerary> days;

  /**
   * Itinerary metadata containing overview information.
   */
  @Data
  @Builder
  @NoArgsConstructor
  @AllArgsConstructor
  public static class ItineraryMetadata {
    
    /**
     * Primary destination city/country.
     * Example: "Tokyo", "Paris", "New York City"
     */
    private String destination;

    /**
     * Trip start date in ISO 8601 format (YYYY-MM-DD).
     * Example: "2024-04-01"
     */
    private String startDate;

    /**
     * Trip end date in ISO 8601 format (YYYY-MM-DD).
     * Example: "2024-04-05"
     */
    private String endDate;

    /**
     * Total number of days in the trip.
     * Example: 5
     */
    private Integer totalDays;

    /**
     * User's budget as a string (with currency).
     * Example: "$2000", "¥200,000", "€1500"
     */
    private String budget;

    /**
     * User's interests/preferences.
     * Example: ["anime", "food", "temples", "shopping"]
     */
    private List<String> interests;
  }

  /**
   * Single day's itinerary within the trip.
   */
  @Data
  @Builder
  @NoArgsConstructor
  @AllArgsConstructor
  public static class DailyItinerary {
    
    /**
     * Day number (1-indexed).
     * Example: 1, 2, 3, ...
     */
    private Integer dayNumber;

    /**
     * Date for this day in ISO 8601 format (YYYY-MM-DD).
     * Example: "2024-04-01"
     */
    private String date;

    /**
     * Theme or title for this day's activities.
     * Example: "Tokyo Arrival: Exploring Shinjuku"
     */
    private String theme;

    /**
     * List of activities for this day in chronological order.
     */
    private List<Activity> activities;

    /**
     * Summary of the day's itinerary.
     * Example: "Start your Tokyo adventure with serene gardens and vibrant nightlife"
     */
    private String summary;
  }

  /**
   * Single activity within a day's itinerary.
   * 
   * <p>The activityId is crucial for frontend linking:
   * when a user clicks an activity card, the frontend can use this ID
   * to find and highlight the corresponding map marker.
   */
  @Data
  @Builder
  @NoArgsConstructor
  @AllArgsConstructor
  public static class Activity {
    
    /**
     * Unique activity identifier for frontend linking.
     * Format: "act-day{dayNumber}-{sequenceNumber}"
     * Example: "act-day1-001", "act-day2-003"
     * 
     * <p>This ID enables bidirectional linking:
     * - Click activity card → highlight map marker with this ID
     * - Click map marker → scroll to activity card with this ID
     */
    private String activityId;

    /**
     * Time range for this activity.
     * Format: "HH:MM-HH:MM" (24-hour format)
     * Example: "09:00-11:00", "14:30-16:00"
     */
    private String time;

    /**
     * Activity title.
     * Example: "Shinjuku Gyoen National Garden", "Sushi Lunch at Tsukiji Market"
     */
    private String title;

    /**
     * Detailed description of the activity.
     * Example: "Explore one of Tokyo's largest and most beautiful parks..."
     */
    private String description;

    /**
     * Activity type (determines icon and styling in frontend).
     */
    private ActivityType type;

    /**
     * Geographic location of this activity (REQUIRED for map integration).
     */
    private Location location;

    /**
     * Travel tips and recommendations for this activity.
     * Example: "Arrive early to avoid crowds", "Bring cash for entrance fee"
     */
    private String tips;

    /**
     * Estimated cost for this activity.
     * Example: "$20", "¥1500", "Free"
     */
    private String estimatedCost;

    /**
     * Estimated duration in minutes.
     * Example: 120 (for 2 hours)
     */
    private Integer durationMinutes;
  }

  /**
   * Geographic location information for an activity.
   * 
   * <p>This data is essential for:
   * <ul>
   *   <li>Plotting markers on Google Maps</li>
   *   <li>Drawing routes between consecutive activities</li>
   *   <li>Calculating distances and travel times</li>
   *   <li>Providing navigation links</li>
   * </ul>
   */
  @Data
  @Builder
  @NoArgsConstructor
  @AllArgsConstructor
  public static class Location {
    
    /**
     * Location name.
     * Example: "Shinjuku Gyoen National Garden", "Tokyo Station"
     */
    private String name;

    /**
     * Full address of the location.
     * Example: "11 Naitomachi, Shinjuku City, Tokyo 160-0014, Japan"
     */
    private String address;

    /**
     * Latitude coordinate (REQUIRED for map plotting).
     * Range: -90 to 90
     * Example: 35.6852
     */
    private Double latitude;

    /**
     * Longitude coordinate (REQUIRED for map plotting).
     * Range: -180 to 180
     * Example: 139.7103
     */
    private Double longitude;

    /**
     * Google Place ID (optional, enables rich place details).
     * Example: "ChIJ4zGFAZmMGGAR_VNKZfyPqvw"
     * 
     * <p>When present, frontend can use Google Places API to fetch:
     * - Photos, reviews, ratings
     * - Opening hours
     * - Contact information
     * - Real-time business status
     */
    private String placeId;

    /**
     * Place type from Google Places API.
     * Example: "temple", "restaurant", "hotel", "museum", "park"
     */
    private String placeType;
  }

  /**
   * Activity type enum (determines frontend icon and styling).
   */
  public enum ActivityType {
    /**
     * Sightseeing activities (museums, landmarks, parks, etc.).
     */
    SIGHTSEEING,

    /**
     * Dining activities (breakfast, lunch, dinner, cafes).
     */
    DINING,

    /**
     * Accommodation (hotel check-in/check-out).
     */
    ACCOMMODATION,

    /**
     * Transportation (flights, trains, bus rides, car rentals).
     */
    TRANSPORTATION,

    /**
     * Shopping activities (markets, malls, boutiques).
     */
    SHOPPING,

    /**
     * Entertainment (shows, concerts, nightlife, sports).
     */
    ENTERTAINMENT
  }
}

