package com.voyageai.voyageaibackend.domain.model;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Structured representation of a travel itinerary with geographic data for map integration.
 * 
 * <p>This model is designed to support rich frontend interactions:
 * <ul>
 *   <li>Display itinerary in a structured, day-by-day format</li>
 *   <li>Plot all locations on an interactive map (Google Maps)</li>
 *   <li>Enable bidirectional linking: click activity → highlight map marker</li>
 *   <li>Enable reverse linking: click map marker → scroll to activity card</li>
 *   <li>Draw daily routes connecting activity locations</li>
 * </ul>
 * 
 * <p>Data source: Generated by AI (OpenAI GPT-4) with geographic coordinates,
 * optionally enriched with Google Places API for precise location data.
 * 
 * <p>Example structure:
 * <pre>
 * {
 *   "metadata": { "destination": "Tokyo", "totalDays": 5, ... },
 *   "days": [
 *     {
 *       "dayNumber": 1,
 *       "date": "2024-04-01",
 *       "theme": "Tokyo Arrival: Exploring Shinjuku",
 *       "activities": [
 *         {
 *           "activityId": "act-day1-001",
 *           "time": "09:00-11:00",
 *           "title": "Shinjuku Gyoen National Garden",
 *           "location": {
 *             "latitude": 35.6852, "longitude": 139.7103, ...
 *           }
 *         }
 *       ]
 *     }
 *   ]
 * }
 * </pre>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class StructuredItinerary {

  /**
   * Itinerary metadata (overview information).
   */
  private ItineraryMetadata metadata;

  /**
   * Daily itineraries in chronological order.
   */
  private List<DailyItinerary> days;

  /**
   * General travel tips (from Python service).
   */
  private List<String> tips;

  /**
   * Itinerary metadata containing overview information.
   */
  @Data
  @Builder
  @NoArgsConstructor
  @AllArgsConstructor
  @JsonIgnoreProperties(ignoreUnknown = true)
  public static class ItineraryMetadata {
    
    /**
     * Primary destination city/country.
     */
    private String destination;

    /**
     * Trip start date in ISO 8601 format (YYYY-MM-DD).
     */
    @JsonAlias("start_date")
    private String startDate;

    /**
     * Trip end date in ISO 8601 format (YYYY-MM-DD).
     */
    @JsonAlias("end_date")
    private String endDate;

    /**
     * Total number of days in the trip.
     */
    @JsonAlias("total_days")
    private Integer totalDays;

    /**
     * User's budget as a string (with currency).
     */
    private String budget;

    /**
     * User's interests/preferences.
     */
    private List<String> interests;
  }

  /**
   * Single day's itinerary within the trip.
   */
  @Data
  @Builder
  @NoArgsConstructor
  @AllArgsConstructor
  @JsonIgnoreProperties(ignoreUnknown = true)
  public static class DailyItinerary {
    
    /**
     * Day number (1-indexed).
     */
    @JsonAlias("day_number")
    private Integer dayNumber;

    /**
     * Date for this day in ISO 8601 format (YYYY-MM-DD).
     */
    private String date;

    /**
     * Theme or title for this day's activities.
     */
    private String theme;

    /**
     * List of activities for this day in chronological order.
     */
    private List<Activity> activities;

    /**
     * Summary of the day's itinerary.
     */
    private String summary;
  }

  /**
   * Single activity within a day's itinerary.
   */
  @Data
  @Builder
  @NoArgsConstructor
  @AllArgsConstructor
  @JsonIgnoreProperties(ignoreUnknown = true)
  public static class Activity {
    
    /**
     * Unique activity identifier for frontend linking.
     * Format: "act-day{dayNumber}-{sequenceNumber}"
     */
    @JsonAlias("activity_id")
    private String activityId;

    /**
     * Time range for this activity (HH:MM-HH:MM).
     */
    private String time;

    /**
     * Activity title.
     */
    private String title;

    /**
     * Detailed description of the activity.
     */
    private String description;

    /**
     * Activity type (determines icon and styling in frontend).
     */
    private ActivityType type;

    /**
     * Geographic location of this activity (REQUIRED for map integration).
     */
    private Location location;

    /**
     * Travel tips and recommendations for this activity.
     */
    private String tips;

    /**
     * Notes (from Python service, alternative to tips).
     */
    private List<String> notes;

    /**
     * Estimated cost for this activity.
     */
    @JsonAlias("estimated_cost")
    private String estimatedCost;

    /**
     * Estimated duration in minutes.
     */
    @JsonAlias("duration_minutes")
    private Integer durationMinutes;
  }

  /**
   * Geographic location information for an activity.
   */
  @Data
  @Builder
  @NoArgsConstructor
  @AllArgsConstructor
  @JsonIgnoreProperties(ignoreUnknown = true)
  public static class Location {
    
    /**
     * Location name.
     */
    private String name;

    /**
     * Full address of the location.
     */
    private String address;

    /**
     * Latitude coordinate (REQUIRED for map plotting).
     */
    private Double latitude;

    /**
     * Longitude coordinate (REQUIRED for map plotting).
     */
    private Double longitude;

    /**
     * Google Place ID (optional, enables rich place details).
     */
    @JsonAlias("place_id")
    private String placeId;

    /**
     * Place type from Google Places API.
     */
    @JsonAlias("place_type")
    private String placeType;
  }

  /**
   * Activity type enum (determines frontend icon and styling).
   */
  public enum ActivityType {
    /**
     * Sightseeing activities (museums, landmarks, parks, etc.).
     */
    SIGHTSEEING,

    /**
     * Dining activities (breakfast, lunch, dinner, cafes).
     */
    DINING,

    /**
     * Accommodation (hotel check-in/check-out).
     */
    ACCOMMODATION,

    /**
     * Transportation (flights, trains, bus rides, car rentals).
     */
    TRANSPORTATION,

    /**
     * Shopping activities (markets, malls, boutiques).
     */
    SHOPPING,

    /**
     * Entertainment (shows, concerts, nightlife, sports).
     */
    ENTERTAINMENT
  }
}

